name: json_schema
version: 1.0.0
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/json_schema
description: >
  Provide support for validating instances against json schema
dependencies:
  #path: ">=0.9.0 < 0.10.0"
  #logging: ">=0.7.1"
  #args: ">=0.13.2"
  path: any
  logging: any
  args: any

# custom <json_schema dependencies>

# end <json_schema dependencies>

dev_dependencies:
  #unittest: ">=0.9.0 < 0.10.0"
  #hop: ">=0.27.0"
  unittest: any
  hop: any

# custom <json_schema dev dependencies>

environment: 
  sdk: ">=0.8.10+6 <2.0.0" 

# end <json_schema dev dependencies>


